language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install pytest-cov
  - pip install -r requirements.txt
script:
  - pytest --cov=sns_boomerang
after_success:
  - codecov
