language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install tox
script:
  - export AWS_DEFAULT_REGION=us-west-2
  - tox -e test -- --cov=sns_boomerang tests
