AWSTemplateFormatVersion: 2010-09-09
Outputs:
  ZappaAppLambdaRoleArn:
    Description: The name of the created IAM role for zappa app Lambda
    Value: !GetAtt BoomerangLambdaRole.Arn
Parameters:
  ReadCapacityUnits:
    ConstraintDescription: should be between 5 and 10000
    Default: "5"
    Description: Provisioned read throughput
    MaxValue: "10000"
    MinValue: "5"
    Type: Number
  WriteCapacityUnits:
    ConstraintDescription: should be between 5 and 10000
    Default: "5"
    Description: Provisioned write throughput
    MaxValue: "10000"
    MinValue: "5"
    Type: Number
Resources:
  BoomerangLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "SnsBoomerangRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
                - lambda.amazonaws.com
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: "DefaultLambdaPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - ec2:AttachNetworkInterface
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                  - ec2:DescribeInstances
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DetachNetworkInterface
                  - ec2:ModifyNetworkInterfaceAttribute
                  - ec2:ResetNetworkInterfaceAttribute
                  - sns:*
                  - sqs:*
                  - route53:*
                Resource:
                  - "*"
        - PolicyName: "DynamoDbStream"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - "arn:aws:dynamodb:::table/table-boomerang-jobs"
                  - "arn:aws:dynamodb:::table/table-boomerang-topics"
        - PolicyName: "S3Bucket"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                  - s3:Delete*
                Resource:
                  - "arn:aws:s3:::lambda-sns-boomerang" # rollbacks bucket
  tableJob:
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: topic
          AttributeType: S
        - AttributeName: version
          AttributeType: N
        - AttributeName: time_due
          AttributeType: N
      GlobalSecondaryIndexes:
        - IndexName: topic-version-index
          KeySchema:
            - AttributeName: topic
              KeyType: HASH
            - AttributeName: version
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref "ReadCapacityUnits"
            WriteCapacityUnits: !Ref "WriteCapacityUnits"
        - IndexName: topic-time_due-index
          KeySchema:
            - AttributeName: topic
              KeyType: HASH
            - AttributeName: time_due
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref "ReadCapacityUnits"
            WriteCapacityUnits: !Ref "WriteCapacityUnits"
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref "ReadCapacityUnits"
        WriteCapacityUnits: !Ref "WriteCapacityUnits"
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: table-boomerang-jobs
      TimeToLiveSpecification:
        AttributeName: time_due
        Enabled: "true"
    Type: AWS::DynamoDB::Table
  tableTopic:
    Properties:
      AttributeDefinitions:
        - AttributeName: topic
          AttributeType: S
      KeySchema:
        - AttributeName: topic
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref "ReadCapacityUnits"
        WriteCapacityUnits: !Ref "WriteCapacityUnits"
      TableName: table-boomerang-topics
    Type: AWS::DynamoDB::Table
